### ISSUE TITLE
add data validation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/user-settings-api#2]
we should validate the data stored so that it can only be the expected object

**Comment by balmas** [comment]
@monzug to test this, you need to pull the webextension build from the the settings branch of the webextension repo https://github.com/alpheios-project/webextension/tree/settingsdev/dist
That's qa-3.0.1.77 but the environment file (env-webext.js) has been changed to point at a dev instance of the user-settings-api at https://settings-dev.alpheios.net.

The instance of the user-settings-api that is deployed there has data validation added to the create and update operations, to try to prevent misuse of our API endpoints.

It requires a regression to make sure creating and updating user options still work as expected (i.e. save an option change, login/logout/login make sure all user options are retrieved)

**Comment by monzug** [comment]
ok.

**Comment by monzug** [comment]
looks good  tested in FF and Chrome.
